// 'use client';
// import StoreProvider from "@/app/StoreProvider";
// import "@/app/globals.css";
// import { Suwannaphum } from "next/font/google";
// import { useEffect, useState } from "react";
// import NoInternetPage from "@/app/no-internet/page"; // Import the NoInternetPage
// import FloatButton from "@/components/home/FloatButton";

// const suwannaphum = Suwannaphum({
//   weight: ["100", "300", "400", "700", "900"],
//   variable: "--font-suwannaphum",
//   display: "swap",
//   subsets: ["khmer"],
// });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const [isOnline, setIsOnline] = useState(true); // Default to true

//   // Check internet status on mount and listen for changes
//   useEffect(() => {
//     // Set initial status
//     setIsOnline(navigator.onLine);

//     // Event listeners for online/offline status
//     const handleOnline = () => setIsOnline(true);
//     const handleOffline = () => setIsOnline(false);

//     window.addEventListener("online", handleOnline);
//     window.addEventListener("offline", handleOffline);

//     // Cleanup listeners on unmount
//     return () => {
//       window.removeEventListener("online", handleOnline);
//       window.removeEventListener("offline", handleOffline);
//     };
//   }, []);

//   return (
//     <html lang="en">
//       <head>
//         <link rel="manifest" href="manifest.json" />
//       </head>
//       <body className={`${suwannaphum.className} bg-background_color`}>
//         <StoreProvider>
//           {isOnline ? children : <NoInternetPage />}
//           <div className="">
//             <FloatButton />
//           </div>
//         </StoreProvider>
//       </body>
//     </html>
//   );
// }

import "@/app/globals.css";
import { Suwannaphum } from "next/font/google";
import ClientWrapper from "@/components/home/ClientWrapper";
import { Metadata } from "next";

const suwannaphum = Suwannaphum({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-suwannaphum",
  display: "swap",
  subsets: ["khmer"],
});

export const metadata: Metadata = {
  title: "CAM-O2  Online Order Products",
  description: "Generated by create next app",
  icons: {
    icon: "/new-logo-o2.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={`${suwannaphum.className} bg-background_color`}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
