import type { Metadata } from "next";
import "@/app/globals.css";
import { Suwannaphum } from "next/font/google";
import NavbarPage from "@/components/Navbar/NavbarPage";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import FloatButton from "@/components/home/FloatButton";
import BannerComponent from "@/components/BannerComponent";

const suwannaphum = Suwannaphum({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-suwannaphum",
  display: "swap",
  subsets: ["khmer"],
});

export const metadata: Metadata = {
  title: "CAM-O2  Online Order Products",
  description: "Generated by create next app",
  icons: {
    icon: "/navbar/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={`${suwannaphum.className} bg-background_color`}>
        <BannerComponent />
        <NavbarPage />
        <main className="w-full">
          <TooltipProvider>
            {children}
            <FloatButton />
          </TooltipProvider>
          <Toaster position="top-center" />
        </main>
      </body>
    </html>
  );
}
